# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca3b2d535702e6c19b22954711b7e189bc8802b453c1a49235e38897ff920a959fad9e626aec2b5b87138f017f8f7f49f6118a2fd1169c458b27b7f17a5a52d2

test:
  secret_key_base: 9bcf98b9187b34fa3e105e4aff514ccf967b0a8189a312ec079b6489af7458665c16441c4e3a2c6caaaf8c97d12bebb47bbf43f0cc07f0e813be09198feb74e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
